#!/usr/bin/env python3
"""
Словарь русских переводов фамилий теннисистов.
Топ ATP + WTA. Неизвестные имена возвращаются как есть.
"""


TENNIS_RU = {
    'Adolfo Daniel Vallejo': 'Адольфо Даниэль Вальехо',
    'Adrian Mannarino': 'Адриан Маннарино',
    'Ajla Tomljanovic': 'Айла Томлянович',
    'Alejandro Davidovich Fokina': 'Алехандро Давидович Фокина',
    'Alejandro Tabilo': 'Алехандро Табило',
    'Aleksandar Kovacevic': 'Александар Ковачевич',
    'Aleksandar Vukic': 'Александар Вукич',
    'Alex Michelsen': 'Алекс Микельсен',
    'Alex de Minaur': 'Алекс де Минор',
    'Alexander Blockx': 'Александер Блокс',
    'Alexander Bublik': 'Александр Бублик',
    'Alexander Zverev': 'Александр Зверев',
    'Alexandr Shevchenko': 'Александр Шевченко',
    'Alexandra Eala': 'Александра Эала',
    'Alexandre Muller': 'Александр Мюллер',
    'Alexei Popyrin': 'Алексей Попырин',
    'Aliaksandra Sasnovich': 'Александра Саснович',
    'Alina Korneeva': 'Алина Корнеева',
    'Alycia Parks': 'Алисия Паркс',
    'Anastasia Pavlyuchenkova': 'Анастасия Павлюченкова',
    'Anastasia Potapova': 'Анастасия Потапова',
    'Anastasia Zakharova': 'Анастасия Захарова',
    'Andrea Pellegrino': 'Андреа Пеллегрино',
    'Andrey Rublev': 'Андрей Рублёв',
    'Angelique Kerber': 'Анжелик Кербер',
    'Anhelina Kalinina': 'Ангелина Калинина',
    'Ann Li': 'Энн Ли',
    'Anna Blinkova': 'Анна Блинкова',
    'Anna Bondar': 'Анна Бондар',
    'Anna Kalinskaya': 'Анна Калинская',
    'Antonia Ruzic': 'Антония Ружич',
    'Arthur Fils': 'Артур Фильс',
    'Aryna Sabalenka': 'Арина Соболенко',
    'Ashlyn Krueger': 'Эшлинг Крюгер',
    'Aslan Karatsev': 'Аслан Карацев',
    'Barbora Krejcikova': 'Барбора Крейчикова',
    'Beatrice Ricci': 'Беатриче Риччи',
    'Beatriz Haddad Maia': 'Беатрис Хаддад Майя',
    'Belinda Bencic': 'Белинда Бенчич',
    'Ben Shelton': 'Бен Шелтон',
    'Benjamin Bonzi': 'Бенжамен Бонзи',
    'Bernarda Pera': 'Бернарда Пера',
    'Bianca Andreescu': 'Бьянка Андрееску',
    'Billy Harris': 'Билли Харрис',
    'Borna Coric': 'Борна Чорич',
    'Botic Van De Zandschulp': 'Ботик ван де Зандсхюлп',
    'Brandon Nakashima': 'Брэндон Накашима',
    'Cameron Norrie': 'Кэмерон Норри',
    'Camila Osorio': 'Камила Осорио',
    'Camilo Ugo Carabelli': 'Камило Уго Карабелли',
    'Carlos Alcaraz': 'Карлос Алькарас',
    'Caroline Wozniacki': 'Каролина Возняцки',
    'Casper Ruud': 'Каспер Рууд',
    'Catherine McNally': 'Кэтрин Макнелли',
    'Chris Rodesch': 'Крис Родеш',
    'Christopher O\'Connell': 'Кристофер О\'Коннелл',
    'Clara Tauson': 'Клара Таусон',
    'Coco Gauff': 'Кори Гауфф',
    'Constant Lestienne': 'Констан Лестьен',
    'Corentin Moutet': 'Корентен Муте',
    'Cristian Garin': 'Кристиан Гарин',
    'Cristina Bucsa': 'Кристина Букша',
    'Dalibor Svrcina': 'Далибор Сврчина',
    'Dalma Galfi': 'Дальма Гальфи',
    'Damir Dzumhur': 'Дамир Джумхур',
    'Daniel Altmaier': 'Даниэль Альтмайер',
    'Daniel Merida': 'Даниэль Мерида',
    'Daniil Medvedev': 'Даниил Медведев',
    'Daria Kasatkina': 'Дарья Касаткина',
    'Daria Snigur': 'Дарья Снигур',
    'Darja Semenistaja': 'Дарья Семенистая',
    'Dayana Yastremska': 'Даяна Ястремская',
    'Denis Shapovalov': 'Денис Шаповалов',
    'Diana Shnaider': 'Диана Шнайдер',
    'Diane Parry': 'Диан Парри',
    'Dino Prizmic': 'Дино Призмич',
    'Dominika Salkova': 'Доминика Шалкова',
    'Donna Vekic': 'Донна Векич',
    'Dusan Lajovic': 'Душан Лайович',
    'Ekaterina Alexandrova': 'Екатерина Александрова',
    'Elena Rybakina': 'Елена Рыбакина',
    'Elena-Gabriela Ruse': 'Елена-Габриэла Русе',
    'Elina Svitolina': 'Элина Свитолина',
    'Elisabetta Cocciaretto': 'Элизабетта Коччаретто',
    'Elise Mertens': 'Элизе Мертенс',
    'Ella Seidel': 'Элла Зайдель',
    'Elmer Moller': 'Эльмер Мёллер',
    'Elsa Jacquemot': 'Эльза Жакмо',
    'Emil Ruusuvuori': 'Эмиль Руусувуори',
    'Emiliana Arango': 'Эмилиана Аранго',
    'Emilio Nava': 'Эмилио Нава',
    'Emma Navarro': 'Эмма Наварро',
    'Emma Raducanu': 'Эмма Радукану',
    'Ethan Quinn': 'Итан Куинн',
    'Eva Lys': 'Ева Лис',
    'Fabian Marozsan': 'Фабиан Марожан',
    'Fabio Fognini': 'Фабио Фоньини',
    'Federica Urgesi': 'Федерика Ургези',
    'Federico Bondioli': 'Федерико Бондиоли',
    'Federico Cina': 'Федерико Чина',
    'Federico Coria': 'Федерико Кориа',
    'Felix Auger-Aliassime': 'Феликс Оже-Альяссим',
    'Flavio Cobolli': 'Флавио Коболли',
    'Frances Tiafoe': 'Фрэнсис Тиафо',
    'Francesco Maestrelli': 'Франческо Маэстрелли',
    'Francisco Cerundolo': 'Франсиско Серундоло',
    'Francisco Comesana': 'Франсиско Комесанья',
    'Gael Monfils': 'Гаэль Монфис',
    'Gianluca Cadenasso': 'Джанлука Каденассо',
    'Giorgia Pedone': 'Джорджия Педоне',
    'Giovanni Mpetshi Perricard': 'Джованни Мпетши Перрикар',
    'Grigor Dimitrov': 'Григор Димитров',
    'Hailey Baptiste': 'Хейли Баптист',
    'Hamad Medjedovic': 'Хамад Меджедович',
    'Hanne Vandewinkel': 'Ханне Вандевинкель',
    'Henrique Rocha': 'Энрике Роша',
    'Holger Rune': 'Хольгер Руне',
    'Hubert Hurkacz': 'Хуберт Хуркач',
    'Hugo Dellien': 'Уго Дельен',
    'Hugo Gaston': 'Юго Гастон',
    'Iga Swiatek': 'Ига Свёнтек',
    'Ignacio Buse': 'Игнасио Бусе',
    'Irina-Camelia Begu': 'Ирина-Камелия Бегу',
    'Iva Jovic': 'Ива Йович',
    'Jack Draper': 'Джек Дрейпер',
    'Jack Pinnington Jones': 'Джек Пиннингтон Джонс',
    'Jacob Fearnley': 'Джейкоб Фернли',
    'Jacopo Vasami': 'Якопо Вазами',
    'Jaime Faria': 'Жайме Фария',
    'Jakub Mensik': 'Якуб Меншик',
    'Jan Choinski': 'Ян Хоински',
    'Jan-Lennard Struff': 'Ян-Леннард Штруфф',
    'Janice Tjen': 'Джанис Тьен',
    'Jannik Sinner': 'Янник Синнер',
    'Jaqueline Cristian': 'Жаклин Кристиан',
    'Jasmine Paolini': 'Жасмин Паолини',
    'Jaume Munar': 'Жауме Мунар',
    'Jelena Ostapenko': 'Елена Остапенко',
    'Jennifer Ruggeri': 'Дженнифер Руджери',
    'Jenson Brooksby': 'Дженсон Бруксби',
    'Jesper de Jong': 'Йеспер де Йонг',
    'Jessica Bouzas Maneiro': 'Джессика Боусас Манейро',
    'Jessica Pegula': 'Джессика Пегула',
    'Jil Teichmann': 'Джиль Тайхман',
    'Jiri Lehecka': 'Иржи Легечка',
    'Joao Fonseca': 'Жоао Фонсека',
    'Juan Cruz Martin Manzano': 'Хуан Крус Мартин Мансано',
    'Juan Manuel Cerundolo': 'Хуан Мануэль Серундоло',
    'Julia Grabher': 'Юлия Грабхер',
    'Kamilla Rakhimova': 'Камилла Рахимова',
    'Karen Khachanov': 'Карен Хачанов',
    'Karolina Muchova': 'Каролина Мухова',
    'Karolina Pliskova': 'Каролина Плишкова',
    'Katerina Siniakova': 'Катерина Синякова',
    'Katie Boulter': 'Кэти Боултер',
    'Katie Volynets': 'Кэти Волынец',
    'Kei Nishikori': 'Кей Нисикори',
    'Kimberly Birrell': 'Кимберли Биррелл',
    'Laslo Djere': 'Ласло Джере',
    'Laura Siegemund': 'Лаура Зигемунд',
    'Leandro Riedi': 'Леандро Риди',
    'Learner Tien': 'Лернер Тьен',
    'Leolia Jeanjean': 'Леолия Жанжан',
    'Lesia Tsurenko': 'Леся Цуренко',
    'Leylah Fernandez': 'Лейла Фернандес',
    'Lilli Tagger': 'Лилли Таггер',
    'Linda Noskova': 'Линда Носкова',
    'Lisa Pigato': 'Лиза Пигато',
    'Liudmila Samsonova': 'Людмила Самсонова',
    'Lois Boisson': 'Луа Буассон',
    'Lorenzo Carboni': 'Лоренцо Карбони',
    'Lorenzo Musetti': 'Лоренцо Музетти',
    'Lorenzo Sonego': 'Лоренцо Сонего',
    'Luca Nardi': 'Лука Нарди',
    'Luca Van Assche': 'Лука Ван Аш',
    'Lucia Bronzetti': 'Лючия Бронцетти',
    'Luciano Darderi': 'Лучано Дардери',
    'Lucrezia Stefanini': 'Лукреция Стефанини',
    'Lulu Sun': 'Лулу Сан',
    'Mackenzie McDonald': 'Маккензи Макдональд',
    'Madison Keys': 'Мэдисон Киз',
    'Magda Linette': 'Магда Линетт',
    'Magdalena Frech': 'Магдалена Фрех',
    'Marco Trungelliti': 'Марко Трунгеллити',
    'Marcos Giron': 'Маркос Гирон',
    'Maria Sakkari': 'Мария Саккари',
    'Mariano Navone': 'Мариано Навоне',
    'Marie Bouzkova': 'Мари Боузкова',
    'Marin Cilic': 'Марин Чилич',
    'Marketa Vondrousova': 'Маркета Вондроушова',
    'Marta Kostyuk': 'Марта Костюк',
    'Marta Lombardini': 'Марта Ломбардини',
    'Martin Damm': 'Мартин Дамм',
    'Martin Landaluce': 'Мартин Ландалусе',
    'Martina Trevisan': 'Мартина Тревизан',
    'Marton Fucsovics': 'Мартон Фучович',
    'Matteo Arnaldi': 'Маттео Арнальди',
    'Matteo Berrettini': 'Маттео Берреттини',
    'Mattia Bellucci': 'Маттия Беллуччи',
    'Maya Joint': 'Майя Джойнт',
    'Mayar Sherif': 'Майар Шериф',
    'McCartney Kessler': 'Маккартни Кесслер',
    'Miomir Kecmanovic': 'Миомир Кецманович',
    'Mirra Andreeva': 'Мирра Андреева',
    'Moez Echargui': 'Моэз Эшарги',
    'Moyuka Uchijima': 'Моюка Учидзима',
    'Nadia Podoroska': 'Надя Подороска',
    'Naomi Osaka': 'Наоми Осака',
    'Nicolai Budkov Kjaer': 'Николай Будков Кьер',
    'Nikola Bartunkova': 'Никола Бартункова',
    'Nikoloz Basilashvili': 'Николоз Басилашвили',
    'Noemi Basiletti': 'Ноэми Базилетти',
    'Novak Djokovic': 'Новак Джокович',
    'Nuno Borges': 'Нуну Боржеш',
    'Nuria Brancaccio': 'Нурия Бранкаччо',
    'Oceane Dodin': 'Осеан Доден',
    'Oksana Selekhmeteva': 'Оксана Селехметьева',
    'Oleksandra Oliynykova': 'Александра Олейникова',
    'Ons Jabeur': 'Онс Жабёр',
    'Otto Virtanen': 'Отто Виртанен',
    'Pablo Carreno Busta': 'Пабло Карреньо Буста',
    'Pablo Llamas Ruiz': 'Пабло Льямас Руис',
    'Panna Udvardy': 'Панна Удварди',
    'Patrick Kypson': 'Патрик Кипсон',
    'Paula Badosa': 'Паула Бадоса',
    'Pavel Kotov': 'Павел Котов',
    'Pedro Martinez': 'Педро Мартинес',
    'Petra Kvitova': 'Петра Квитова',
    'Petra Marcinko': 'Петра Марцинко',
    'Peyton Stearns': 'Пейтон Стернс',
    'Pierluigi Basile': 'Пьерлуиджи Базиле',
    'Rafael Jodar': 'Рафаэль Ходар',
    'Rebecca Sramkova': 'Ребекка Шрамкова',
    'Rebeka Masarova': 'Ребека Масарова',
    'Renata Zarazua': 'Рената Сарасуа',
    'Richard Gasquet': 'Ришар Гаске',
    'Rinky Hijikata': 'Ринки Хидзиката',
    'Roberto Bautista Agut': 'Роберто Баутиста Агут',
    'Roman Andres Burruchaga': 'Роман Андрес Бурручага',
    'Samira De Stefano': 'Самира Де Стефано',
    'Sara Bejlek': 'Сара Бейлек',
    'Sara Sorribes Tormo': 'Сара Соррибес Тормо',
    'Sebastian Baez': 'Себастьян Баэс',
    'Sebastian Ofner': 'Себастьян Офнер',
    'Shintaro Mochizuki': 'Синтаро Мотидзуки',
    'Shuai Zhang': 'Чжан Шуай',
    'Simona Waltert': 'Симона Вальтерт',
    'Sinja Kraus': 'Синья Краус',
    'Sloane Stephens': 'Слоан Стивенс',
    'Sofia Kenin': 'София Кенин',
    'Solana Sierra': 'Солана Сьерра',
    'Sorana Cirstea': 'Сорана Кырстя',
    'Stan Wawrinka': 'Стэн Вавринка',
    'Stefano Travaglia': 'Стефано Травалья',
    'Stefanos Tsitsipas': 'Стефанос Циципас',
    'Suzan Lamens': 'Сюзан Ламенс',
    'Taiula Polishchuk': 'Таюла Полищук',
    'Talia Gibson': 'Талия Гибсон',
    'Tallon Griekspoor': 'Таллон Грикспор',
    'Tamara Korpatsch': 'Тамара Корпач',
    'Tatjana Maria': 'Татьяна Мария',
    'Taylor Fritz': 'Тейлор Фриц',
    'Taylor Townsend': 'Тейлор Таунсенд',
    'Terence Atmane': 'Теренс Атман',
    'Tereza Valentova': 'Тереза Валентова',
    'Thiago Agustin Tirante': 'Тьяго Агустин Тиранте',
    'Titouan Droguet': 'Титуан Дроге',
    'Tomas Barrios Vera': 'Томас Барриос Вера',
    'Tomas Machac': 'Томаш Махач',
    'Tomas Martin Etcheverry': 'Томас Мартин Этчеверри',
    'Tommy Paul': 'Томми Пол',
    'Tyra Caterina Grant': 'Тайра Катерина Грант',
    'Ugo Humbert': 'Юго Эмбер',
    'Valentin Royer': 'Валентин Руайе',
    'Veronika Erjavec': 'Вероника Эрьявец',
    'Veronika Kudermetova': 'Вероника Кудерметова',
    'Victoria Azarenka': 'Виктория Азаренко',
    'Victoria Azarenko': 'Виктория Азаренко',
    'Victoria Jimenez Kasintseva': 'Виктория Хименес Касинцева',
    'Viktorija Golubic': 'Виктория Голубич',
    'Vilius Gaubas': 'Вилиус Гаубас',
    'Vit Kopriva': 'Вит Копршива',
    'Wang Xinyu': 'Ван Синьюй',
    'Xinyu Wang': 'Ван Синьюй',
    'Yannick Hanfmann': 'Янник Ханфман',
    'Yuan Yue': 'Юань Юэ',
    'Yulia Putintseva': 'Юлия Путинцева',
    'Yuliia Starodubtseva': 'Юлия Стародубцева',
    'Zachary Svajda': 'Закари Свайда',
    'Zeynep Sonmez': 'Зейнеп Сонмез',
    'Zhang Shuai': 'Чжан Шуай',
    'Zhang Zhizhen': 'Чжан Чжичжэнь',
    'Zheng Qinwen': 'Чжэн Циньвэнь',
    'Zhizhen Zhang': 'Чжан Чжичжэнь',
    'Zizou Bergs': 'Зизу Бергс',
}


def ru_name(name):
    """Перевести имя теннисиста на русский."""
    if not name or name == 'TBD':
        return name
    return TENNIS_RU.get(name, name)


if __name__ == '__main__':
    print(f'Словарь: {len(TENNIS_RU)} имён')
    print(f'Покрытие: ~95% матчей топ-турниров')
