server {
    listen 80;
    server_name _;

    root /var/www/sport;
    index index.html;

    location = / {
        return 301 /news.html;
    }

    location / {
        try_files $uri $uri/ /news.html;
    }

    location /static/ {
        alias /var/www/sport/static/;
        expires 1h;
    }
}
